title:		Mapping College Resources
github:		https://github.com/nudge4/map_resources	
site:		https://nudge4.github.io
baseurl: 	'.'

# mapboxgl-js version
mbgl_ver:       '0.42.2'

# assets
images:         './assets/images'
css:            './assets/css'
js:             './assets/js'
data:           './assets/data'
mapdata:        './assets/data/map_data.csv'

# style
highlighter:    rouge
permalink:      pretty

# map options
mapstyle:	light-v9

# web app icon
icon:
  shortname:    'Advising'
  longname:     'College Advising Resources Interactive Map'

# google form
form:		https://docs.google.com/forms/d/e/1FAIpQLSeCRvaZzvvBONPy11AJ2m7da-N2GC0f_pGcvEGBUSBHW46dyg/viewform