title:		Mapping College Resources
github:		https://github.com/edpowo/map_resources	
site:		https://edpowo.github.io
baseurl: 	'/map_resources'

# mapboxgl-js version
mbgl_ver:       '0.42.2'

# assets
images:         '/map_resources/assets/images'
css:            '/map_resources/assets/css'
js:             '/map_resources/assets/js'
data:           '/map_resources/assets/data'

# style
highlighter:    rouge
permalink:      pretty

# map options
mapstyle:	light-v9

# web app icon
icon:
  shortname:    'Advising'
  longname:     'College Advising Resources Interactive Map'
