title:		Mapping College Resources
github:		https://github.com/nudge4/map_resources	
site:		https://nudge4.github.io
baseurl: 	'/map_resources'

# mapboxgl-js version
mbgl_ver:       '0.42.2'

# assets
images:         '/map_resources/assets/images'
css:            '/map_resources/assets/css'
js:             '/map_resources/assets/js'
data:           '/map_resources/assets/data'
mapdata:        '/map_resources/assets/data/map_data.csv'

# style
highlighter:    rouge
permalink:      pretty

# map options
mapstyle:	light-v9

# web app icon
icon:
  shortname:    'Advising'
  longname:     'College Advising Resources Interactive Map'

# google form
form:		https://docs.google.com/forms/d/e/1FAIpQLSeh6qqOwji2q8oEEKWEMR8T5pyoQZCc6oN4oO9d_CtyTAEvfg/viewform
