title:		Mapping College Resources
github:		https://github.com/edpowo/map_resources	
site:		https://edpowo.github.io
baseurl: 	'map_resources'

highlighter:    rouge
permalink:      pretty

# Map options
mapstyle:	light-v9
